from __future__ import annotations


NEGATION_QUERY_TOKENS = {"deny", "denied", "denies", "no", "not", "without"}
NEGATED_LABEL_PREFIXES = (
    "no ",
    "not ",
    "without ",
    "absence of ",
    "negative for ",
    "denies ",
    "denied ",
)
NEGATED_LABEL_TOKENS = {"absent", "absence", "denied", "denies", "negative", "no", "not", "without"}
DENIED_POSITIVE_FINDING_STRONG_PENALTY = 0.52
DENIED_POSITIVE_FINDING_WEAK_PENALTY = 0.40
DENIED_CONTEXT_MISMATCH_PENALTY = 0.24
NUMERIC_CONTEXT_FRAGMENT_PENALTY = 0.34
DENIAL_SCOPE_BREAK_BIGRAMS = {
    ("vital", "sign"),
}
ALLOWED_DENIAL_ANCHOR_SPANS = {
    ("weight", "loss"),
}
GENERIC_LABEL_TEXTS = {
    "attribute type",
    "acute infectious disease",
    "acute infection disease",
    "communicable disease",
    "history",
    "significant",
    "possible",
    "diagnostic",
    "diagnosis",
    "evaluation",
    "facilities utilization",
    "facility utilization",
    "fraction",
    "monitoring",
    "probable diagnosis",
    "likely diagnosis",
    "scheduling",
    "symptoms",
    "return",
    "worsen",
    "studies",
    "patient advised to",
    "drug",
    "drugs",
    "medication",
    "medications",
    "pharmaceutical preparation",
    "pharmaceutical preparations",
    "therapeutic procedure",
    "tests",
    "tests and testing",
    "type",
    "type attribute",
    "type property qualifier value",
    "with type",
    "no evidence of",
    "difficult",
    "difficulty",
    "difficulty with",
    "has difficulty doing",
    "worse",
    "worsening",
}
LOW_SPECIFICITY_QUERY_TOKENS = {
    "absence",
    "absent",
    "after",
    "before",
    "clinical",
    "controlled",
    "diagnostic",
    "diagnosis",
    "drug",
    "drugs",
    "difficult",
    "difficulties",
    "difficulty",
    "exam",
    "examination",
    "evaluation",
    "finding",
    "findings",
    "he",
    "likely",
    "level",
    "levels",
    "measure",
    "measurement",
    "measurements",
    "medical",
    "medication",
    "medications",
    "high",
    "loss",
    "person",
    "pharmaceutical",
    "preparation",
    "preparations",
    "physical",
    "place",
    "she",
    "operation",
    "operations",
    "operative",
    "poorly",
    "probable",
    "procedure",
    "procedures",
    "regular",
    "review",
    "reviewed",
    "reviews",
    "risk",
    "risks",
    "study",
    "studies",
    "surgery",
    "surgeries",
    "surgical",
    "test",
    "tests",
    "their",
    "they",
    "time",
    "while",
    "worse",
    "worsening",
}
BROAD_PRIMARY_LABEL_TEXTS = {
    "acute infectious disease",
    "acute infection disease",
    "communicable disease",
    "diagnosis",
    "facilities utilization",
    "facility utilization",
    "fraction",
    "heart disease",
    "likely diagnosis",
    "probable diagnosis",
    "therapeutic procedure",
}
INFECTION_SITE_TOKENS = {
    "abdominal",
    "abdomen",
    "bladder",
    "bloodstream",
    "bone",
    "catheter",
    "central",
    "cellulitis",
    "cervical",
    "foot",
    "kidney",
    "line",
    "lung",
    "pelvic",
    "pulmonary",
    "respiratory",
    "skin",
    "tract",
    "urinary",
    "urine",
}
NORMAL_EXAM_CONTEXT_TOKENS = {
    "alert",
    "auscultation",
    "bilateral",
    "bilaterally",
    "clear",
    "exam",
    "examination",
    "oriented",
    "physical",
    "regular",
}
NORMAL_EXAM_FRAGMENT_TOKENS = {
    "heart",
    "lung",
}
NORMAL_EXAM_ALLOWED_LABEL_TOKENS = {
    "alert",
    "auscultation",
    "clear",
    "edema",
    "murmur",
    "normal",
    "oriented",
    "peripheral",
    "sound",
}
DENIAL_SCOPE_BREAK_AFTER_WITHOUT_AND = NORMAL_EXAM_CONTEXT_TOKENS | NORMAL_EXAM_FRAGMENT_TOKENS
FRAGMENT_SEMANTIC_TYPES = {
    "anatomical structure",
    "body location or region",
    "body part, organ, or organ component",
    "body space or junction",
    "cell",
    "cell component",
    "embryonic structure",
    "fully formed anatomical structure",
    "tissue",
}
MODIFIER_FRAGMENT_LABEL_TOKENS = {
    "abnormal",
    "decrease",
    "decreased",
    "elevated",
    "high",
    "increase",
    "increased",
    "low",
    "mild",
    "mildly",
    "moderate",
    "moderately",
    "reduced",
    "reduction",
    "reducing",
    "severe",
    "severely",
}
MODIFIER_FRAGMENT_SEMANTIC_TYPES = {
    "clinical attribute",
    "finding",
    "qualitative concept",
    "quantitative concept",
}
MODIFIER_FRAGMENT_PENALTY = 0.62
COMPOSITE_CONTEXT_SEMANTIC_TYPES = {
    "disease or syndrome",
    "finding",
    "pathologic function",
    "sign or symptom",
}
SEPSIS_SHOCK_ANCHOR_TOKENS = {
    "hypotension",
    "norepinephrine",
    "perfusion",
    "pressor",
    "vasopressin",
    "vasopressor",
}
NUMERIC_SPECIFICITY_CONTEXT_TOKENS = {
    "class",
    "grade",
    "stage",
    "type",
}
SEPSIS_ETIOLOGY_SUBTYPE_TOKENS = {
    "bacterial",
    "candida",
    "clostridial",
    "clostridium",
    "coli",
    "escherichia",
    "fungal",
    "gram",
    "klebsiella",
    "meningococcal",
    "pneumococcal",
    "pseudomonas",
    "staphylococcal",
    "streptococcal",
}
PROCEDURE_LABEL_SUFFIXES = (
    "centesis",
    "desis",
    "ectomy",
    "lysis",
    "ostomy",
    "otomy",
    "pexy",
    "plasty",
    "rrhaphy",
    "scopy",
)
COGNITIVE_MEMORY_CONTEXT_TOKENS = {
    "amnesia",
    "cognitive",
    "dementia",
    "forget",
    "memory",
    "medication",
}
COGNITIVE_MEMORY_LABEL_TOKENS = {
    "amnesia",
    "cognitive",
    "dementia",
    "forget",
    "impairment",
}
THERAPY_TRANSITION_CONTEXT_TOKENS = {
    "discharge",
    "facility",
    "nursing",
    "physical",
    "skilled",
    "therapy",
}
THERAPY_TRANSITION_ALLOWED_LABEL_TOKENS = {
    "discharge",
    "facility",
    "home",
    "nursing",
    "physical",
    "rehabilitation",
    "skilled",
}
